version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:0.56.0
    restart: unless-stopped
    command: /bin/sh -c 'INSTANCE_IP=$$(hostname -i) node main.js'
    mem_limit: 4G
    volumes:
     - ./data/uploads:/app/uploads
     - /tmp:/tmp
    environment:
     - PORT=3000
     - ROOT_URL=http://rocketchat.dev
     - MONGO_URL=mongodb://mongo:27017/rocketchat
     - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: rocketchat.dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/dump

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: traefik --web --docker --defaultentrypoints=http --entryPoints='Name:http Address::3000'
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hubot:
    image: rocketchat/hubot-rocketchat:1.0.8
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=hubot
      - ROCKETCHAT_PASSWORD=your-random-pass
      - BOT_NAME=hubot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-isup,hubot-memes
      - MONGODB_URL=mongodb://mongo:27017/hubot-brain
      - TZ=/usr/share/zoneinfo/Europe/Berlin
    links:
      - rocketchat:rocketchat
      - mongo:mongo
    volumes:
      - ./data/hubotscripts:/home/hubot/scripts
    ports:
      - 3001:8080
