version: '2'

services:
  grafana:
    image: grafana/grafana:6.6.2
    restart: unless-stopped
    ports:
      - 3300:3000
    volumes:
      - ./data/config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./data/config/grafana/provisioning/dashboards/provider:/etc/grafana/provisioning/dashboards:ro
      - ./data/config/grafana/provisioning/dashboards/json-exports:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  prometheus:
    image: quay.io/prometheus/prometheus:v2.16.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./data/prometheus:/prometheus
      - ./data/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - rocketchat
      - cadvisor
      - node-exporter

  cadvisor:
    image: google/cadvisor:v0.33.0
    restart: unless-stopped
    volumes:
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: quay.io/prometheus/node-exporter:v0.18.1
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
